# Generated by Django 5.1.1 on 2025-01-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image_url',
            field=models.URLField(default='images/community-default.webp'),
        ),
    ]
