# Generated by Django 5.1.1 on 2025-01-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image_url',
            field=models.CharField(blank=True, default='http://localhost:8000/static/images/community-default.webp', null=True),
        ),
    ]
