# Generated by Django 5.1.1 on 2025-02-01 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_communitymember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='communities.community'),
        ),
    ]
